* Spring 2022 Reviews
** OP
Howdy,

I'm finished with the shows from this season and melting into a puddle of sweat and eyeballs, so seems like a perfect time to send this.

** Qian Cong Shou
It's not the show's fault that I don't speak Chinese, but I certainly don't. And it's not the fan subbers' responsibility to translate the show well, but they certainly didn't. That or the show lobbed a whole bunch of hooey at me and expected it to stick like a bowl of cold pudding in the face when it just confused me like a bowl of cold pudding in the face. That's not to say it's a bad show. Yes, the characters are your typical shonen archetypes. Yes, those shonen archetypes are: "yells and hurts self", "broods" and "girl". Yes, the climactic moment of the 15 episode season brings in a previously unmentioned big bad, severs the most meaningful connection the main character forged, and basically wraps on "at least *shrugs* we're better friends *shrugs* now". This really felt like the adaptation of a manga I wouldn't like, in that it: introduced a whole bunch of stuff in episode one, kind of fucked around for the next four episodes, taunted me with the faintest whiff of plot, then fucked around until the climax.

There was some really fun CG action scenes and impact frames integrated into the action in fun ways. Impact frames used in such an extended manner that they don't really count as frames so much as the animators chose to do smeary black-and-white animation for stretches.

5/10 Most Objects with Faces for All the Objects with Faces

** Paripi Koumei
I am still genuinely tickled by the premise of this show and was looking forward to seeing Koumei and his wacky friends stretch ancient war tactics to fit the music industry. Sure, we got some of that, but the friends weren't nearly as wacky as I'd thought. Eiko and Kabe in particular came off as very earnest and the highlights of the show for me came when they were played off against a sillier character. Even Nanami being the pawn/figurehead/<some war analogy> of an underhanded producer got me more invested than the girl who runs and sings. Despite my disinterest in the characters, there were still memorable moments: Koumei trapping hundreds of dancers in a club, Koumei tracking Kabe into the laundromat, Koumei apparently having a secret blackmail (?) plan that never got revealed. I just enjoy Koumei.

7/10: Most Sunglasses for All the Sunglasses

** Aharen-san
I'm not sure if this show had a lot of gags or about five that they wrung the ever-living snot out of. For the record, those five would be: "Aharen gets close to Raido", "Raido jumps to conclusions", "We found Oshiro!", "Cute mascot character", and "Cultural reference". "But what about the "Such esteem!" teacher" you may ask. Subset of AGC2R of course. "But what about Aharen crushing Raido at games?" you may inquire. Mix of RJ2C and a reverse AGC2R since Raido assumes he can ever match Aharen at anything and for Aharen to get close to Raido she must start out far away (in terms of skill at reversi). "But what about Aharen's younger sister being taller than her? Or her younger brother dressing like her?" you may demand. First, stop asking so many questions while I'm in the middle of writing down my thoughts, please. Second, those are not funny. Okay, I've sufficiently convinced myself that there's no particular reason to have enjoyed this show. But I still enjoyed it.

6/10 Most Crane Game Footage for All the Crane Game Footage

** Komi-san
My favorite ending (credits scene)! I love that pixelated, color block, rotoscope look.

There are some interesting retreads from the first season. In terms of the "introduce a character, have them interact strangely with Komi" bit which works well enough. But also, there's definitely an episode schema where we watch some situation play out from the perspective of either (a) Komi or (b) the gang, cue awkward, youthful hijinks. Then, we watch the same events from the other's perspective, cue fumbling, naive shenanigans plus an "Aww" moment for Komi. Examples from this season include the Christmas episode and the beginning of episode 7 where Komi and Tadano see each other in school after Tadano's sick day. It's a fun format and fits well with the main gag driver/miscommunication of the series "Komi intimidates people into leaving her alone, but is also too shy to reach out to them". There were some sweet moments, but probably nothing will be as sweet as the first episode of the first season, so my highlights were more often the gag moments like the second "Would you date her?" bit, Yamai trying to oggle/grope Komi, and the Eraser War.

7/10 Best Character Running with Another Character's Tights on Their Head Scene for Yamai and Komi's Tights

** Ao Ashi
I'm 90% sure there was rotoscoped action in a couple episodes (2 and 9) but it was so brief that I'm not relying on seeing any more in the second half. Even though it would be super cool to see a rotoscoped soccer anime, there were still some good action scenes and we've finally made it to the point where Aoi can learn tactics and teamwork instead of just winning with the power of his forceful gaze.

** Dance Dance Danseur
One of the shows of this season where the opening or ending scenes disregard the character designs (along with Ao Ashi's ending). They managed to get to a good ending point and had some really neat dance animation (and Luou's scary, smeary scenes) along with some stiff, animation-light episodes. But the manga itself doesn't devote much space to extended dance sequences so getting any of them was nice. I was surprised that the second-half of the season didn't involve much CG for the dance scenes. It wasn't that I was eager to see them, but there were some interesting efforts to make the CG blend in during episode 5 (overhead shots, shooting the dancers' shadows, some scritchy-scratchy effects over the figures). And having them crop up in only one episode just leaves me a little confused (like there was definitely some consideration given to it, but was that the main studio's choice or some contractor?).

7/10 Best Old Person Face for the Grandmother

** Spy x Family
Like being poked repeatedly in the cheek with a cooked carrot. At first you ignore it and stay stoic. Then, the carrot starts to disintegrate in the poker's hands and you feel the ridiculousness of the situation. Eventually, you're covered in carrot mush and can't help laughing. That's how I feel about the little moments, mostly Anya-driven, that were regularly getting chuckles out of me by the end of the season. "Woow." "Wait! Papa who is a good and normal person." Those probably wouldn't have been nearly as amusing if they hadn't been preceded by hours of cute silliness, but that doesn't take away from their enjoyability. Plus, this is absurdly well-animated for a comedy show and was a great successor to Vanitas for "Cool European city street scenes" this season.

8/10 Best Book Series for the "... for a good child" series ("Arithmetic for a good child", "Language for a good child", ...)

** Honzuki
The first season is still the high-water mark for me, the action scenes and having Myne recall things from her world for other folks to create isn't as fun as seeing the experimentation and struggle from her perspective. There were definitely some emotional moments, but I felt they were played off as "Myne wants to be with her family, but people are stopping her" rather than getting into the dichotomy between that desire and, for example, Delia's desire to stay with Dirk. Didn't Myne mention that she had a younger sister in her old life, that seems like something that could have been explored more fully. But I'd still rather have those sorts of parallels receive a too-light touch than be shoved down my throat.

At one point, I became a bit confused by what plot justifications I was just having trouble grasping because this is a feudal society, and which ones were poorly justified. But when I gave myself in to just trusting the story, it became more enjoyable.

7/10 Best Character Design for "This dude is fat, so gotta be evil"

** Summertime Render
I'm conducting a scavenger hunt while watching this, but I won't reveal what it's for until the series ends.

** Shokei Shouji
Dropped after episode 7.

** Koi wa Sekai Seifuku no Ato de
I started this because I was so tickled by the premise of Paripi Koumei that I thought, "Maybe a show with another silly premise will be good." I definitely laughed more at this show than Koumei (even though that's not a fair comparison). Whenever the premise of "superheroes as celebrities and supervillains as an evil corporation" was taken seriously, it got at least a chuckle out of me. "Let's put our main heroine in a situation where she's going to be turned into a giant monster." Of course, her main concern is how to turn down the promotion without disappointing friends and family. I don't have a second example as good as that one, and if I did then it would have taken this show from just fun to actually funny. As it is, there were a few clever pieces in a relatively inoffensive package. The animation was just meh (the henshin scenes were aiming more for comedy than impact), except for the final episode where we got some really good character animation for a funky monster and the fight against it.

7/10 Best Pronunciation for "Wread Jeelautoh"

** Vampire in the Garden
My pick for most vibe-y show of the season. Steampunk, snowpunk, vampires and samurai. There were good action scenes, but the show felt stuck between some episodic road trip movie and a mystery. It was a good enough example of the first genre, but the mystery was a less interesting version of the "Fena: Pirate Princess" "Let's find a place"-type mystery. And I think of the road trip genre being elevated by the dynamic between main characters, where this show's two protagonists were a little tame. There was a sort of "power dynamic shift" over the course of the series and an underlying theme of music tying them together, but the former came off as begruding ("*sigh* fine, if we have to, we'll give this character growth") and the latter went in and out for me. The vibe really was great though.

6/10 Most "Hey! Why wasn't this just a movie?" for "Hey! They're shoehorning pseudo-cliffhangers into this Bonny and Clyde story and it kinda sucks."

** ED
Adios,
Eric

** Follow-up
Hey, I remember the part in Hamlet where the characters played Truth or Dare.

Hamlet: I dare you to tell me the last person you killed?

Claudius: ...

Gertrude: I did have a poor killed last week for poor-ing in my line of sight.

Claudius: Oh Gertrude, I want to jump your bones.

Ophelia: I killed the beat at my last dance battle. Does that count?

Hamlet: Drat, my ingenious plan failed.
