* Bear-related
** Feeding honey to a bear
   While feeding honey to a bear,

   I fix him with a fearsome stare.  

   The bear (Carl) asks for more.  

   Should I go to the store?  

   Would Carl take my pocket eclair?  

** Bear hair
   Stab the bear! Stab the bear!

   It has valuable hair.

   If we skin it,

   There's no limit

   To the clothes we can wear.

** Ro-bear Gerard
   The robot bear punches the ground.

   It causes shockwaves all around.

   Gerard is a stud,

   My new bestest bud.

   Just a dangerous, cuddly mound.
* Cow/fairy-related
** Canary in a cow-mine
   Fearing from fourteen fierce fairies,
   
   Cows contacted a canary.
   
   But it was bird-brained.
   
   No peace was obtained.
   
   Heffers' helper made things hairy.

* Ferret/flamingo-related
** Furry Furrowers
   Fearful of four fighting flamingoes,

   Ferrets find fulfillment in furrows.

   After finding fields fallow

   Few tell the rest to follow.

   Fellow ferrets face their final foes.

* Horse-related
** Yum
   Faced with no recourse

   I ate a dead horse

   Its meat was sweet,

   From nose to feet.

   I've stolen its force.
* Love poems
** Blinded
   Yesterday you stole my vision,

   Blinded by a strong emission.

   You were so bright

   That I lost my sight.

   In love with nuclear fission.
* Plumbing poems
** Clogged
   My sink is clogged

   and it's stressing me out.

   Onto the log,

   'til sanity's worn out.
* Spooky
** Haunted Jaunt
   There once was a boy out on a jaunt.

   But none need fear that them he would haunt.

   For the boy was a ghost.

   On his mind the foremost
   
   Pale spectral trails he wanted to flaunt.


   If by chance you e'er meet a specter,

   You should not run or try to hector.

   What would strike a ghoul dumb

   Is the juice of a plum.

   Not a one can resist that nectar.
* Train/star-related
** Going Home
   Riding home backwards,

   Guarding the front of the train.

   The Sun's in my eyes.
