* Conversations
** Bees
A: I ran into a great number of bees on my walk yesterday.

B: That sounds frightening, how did you get away?

A: Get away? I didn't have to. There's no need to run from no bees.
** Chemistry
A: I'm so glad we matched.

B: Likewise, I've matched with a few others, but noone who I really had chemistry with.

A: Hold up, you need to have chemistry to donate your kidney to me?

B: Yup
** Deer
A: How does a deer make an origami bell?

B: ?

A: Folding
** Did you know?
A: Did you know that humans only use 10% of their fingers?

B: ?

A: *Holds up 10 fingers*
** England
A: In England they call the nuclear football the nuclear American football.

B: ...
** Fish
A: You must become one with these goldfish.

B: *swims*

B: *hugs fish*

A: You have failed. The correct answer was to eat them.
** Fraud
A: Fraud used to be so much easier back in the old days. Back when the Social Security numbers were so low. And it was only a bunch of white guys who we considered people. You could just walk up to a bank, say, Hello, I'm Charles Pumpkins, SSN 35, and I would like to withdraw $10" and walk out with enough money to buy a horse.

B: ?

A: Or two.
** Hey
A: *Hands behind back, walks up to B*

A: Hey, what would you like to be remembered for after next Tuesday?

B: ?

A: Sorry, "after you die"?

A: (≧︿≦)
** Hip replacements
A: What if *hehe*

B: ?

A: Hip replacements were lambs?

B: ?

A: So they just replaced hips with lambs?

B: ?

A: *hehe*
** Magic hat
A: Hey kid, here's a magic top hat that brings inanimate objects to life. Let's use it on your snowman!

B: *Walks into backyard*

B: *Digs up a shoebox*

B: *Puts the top hat on a dead rabbit*
** Movie
A: I just watched "Fast & Pious".

B: ...
** Name
A: My name is Eric.

B: How do you spell that?

A: E as in Edward, R as in Redward, I as in Iredward, C as in Ciredward.
** Remember
A: I can remember my pasta lives.

B: ...
** Sleepy
A: What do you need when you're sleepy after a drug night high?

B: ?

A: A pillow
** Steve
A: "Steve Jobs"? Were you friends with him?

B: Why?

A: Because you're referring to him so informally. I always call him "Steve Employment".
** Weight lifting
A: I'm trying to learn something new.

B: What?

A: How to lift 500 lbs.
* Missayings
** Bad luck
If you break a mirror's heart you get 7 years bad luck.
** Candy
Pitiful as an adult taking candy from a baby.
** Early
So early that the dawn was still smooth.
** Easy-peasy
Easy-peasy like playing parcheesi.
** Fish in a barrel
Unsatisfying as shooting fish in a barrel.
** Honey
You catch more flies with honey than without honey.
** Marriage
Gloveless marriage
** Moon
The moon is made of keys.
** One man's trash
One man's trash is another man.
** Pen
The pen is inkier than the sword.
** When life gives you ...
When life gives you melons, make lemonade.
* Word break rearranging
** Low self-esteem
Lowe's elf esteem
