* Bear-related
** Bear hair
   Stab the bear! Stab the bear!

   It has valuable hair.

   If we skin it,

   There's no limit

   To the clothes we can wear.
** Danger
Animals barely conceive

Dangers existential.

Following grievous hazards

Just koala's last meal.

Nobody opens quail roosts,

Stridently trespassing.

Unless welcome's xenial

Yon' zoa ... Attacking!
** Feeding honey to a bear
   While feeding honey to a bear,

   I fix him with a fearsome stare.  

   The bear (Carl) asks for more.  

   Should I go to the store?  

   Would Carl take my pocket eclair?  

** Ro-bear Gerard
   The robot bear punches the ground.

   It causes shockwaves all around.

   Gerard is a stud,

   My new bestest bud.

   Just a dangerous, cuddly mound.
* Book-ish
** Book recommendation
Book recommendation

Causes perspiration.

Will my favorite tome

Find itself a new home?

Or will a misplaced line

See it out on its spine?
* CheesE
** PartE
Flexible collectibles

Are objectively delectable.

Set your table with staples

For a neighbor to come and nibble.

A brand new dinner party

Serving elastic cheese, havarti.
* Cow/fairy-related
** Canary in a cow-mine
   Fearing from fourteen fierce fairies,
   
   Cows contacted a canary.
   
   But it was bird-brained.
   
   No peace was obtained.
   
   Heffers' helper made things hairy.

* Family/telemarketing-related
** Good boy
I had a post-op visit the other day

and e-mailed my family to let them know

the results. I included the line "was told

I'm a good boy whose knee is recovering".

My mom wrote back first with, "You ARE a good boy!"

My dad wrote back, "you're much more than a good boy

you're the best", and I detected a trend here.

"Who's a good boy? You are! Yes, you are!" came from

my brother. It was comforting to see that

we all have the same email "Yes and" impulse.

They all sent their responses to me alone.
** I don't like talking on the phone
I had a fifteen minute phone

conversation with my dad tonight.

Then a twenty minute call which

turned out to be asking me to give

money to my grad program. I

left both calls feeling equal amounts

of icky weirdness. In one, I

felt bad for not giving more time

to this man who I should feel close

to. In the other, I felt bad for

being too eager to talk to

a complete stranger, who showed a small

amount of interest in my life.
* Feelings (blech)
** Absurd
What could be more absurd

Than an unspoken word?

Leaving 'til we are dead,

Those feelings left unsaid.

They exist in my mind,

Left where you cannot find

My fearful apathy.

A stubborn empathy.
* Ferret/flamingo-related
** Furry Furrowers
   Fearful of four fighting flamingoes,

   Ferrets find fulfillment in furrows.

   After finding fields fallow

   Few tell the rest to follow.

   Fellow ferrets face their final foes.

* Horse-related
** Yum
   Faced with no recourse

   I ate a dead horse

   Its meat was sweet,

   From nose to feet.

   I've stolen its force.
* Hot stuff
** Arson
Fueled by desire

To light a fire

An arsonist

Must use their fist

To keep a spark

Safe from the dark
* Legs (one or more)
** Olive oil store
Chit chatting on the chairs

At the olive oil store.

Child kicking up her legs
* Love poems
** Blinded
   Yesterday you stole my vision,

   Blinded by a strong emission.

   You were so bright

   That I lost my sight.

   In love with nuclear fission.
* Paper, that thin stuff that comes from trees, you know?
** Paper Airplane
Any breeze can doom 'em.

Fragile, geez how "if-you-know-you-know".

Jeopardies keep loomin',

must-maybes nearly over-o'er-throw.
* Plumbing poems
** Clogged
   My sink is clogged

   and it's stressing me out.

   Onto the log,

   'til sanity's worn out.
** Leaky faucet
Heartbeats like a leaky faucet,

Sleeping like a newborn deer.
* Poe-tree
** Huh
A tree made full with flowers

Could be stared at for hours.

Try to peek inside

To see what may hide.

Maybe one of those tree showers?
* Spooky
** Haunted Jaunt
   There once was a boy out on a jaunt.

   But none need fear that them he would haunt.

   For the boy was a ghost.

   On his mind the foremost
   
   Pale spectral trails he wanted to flaunt.


   If by chance you e'er meet a specter,

   You should not run or try to hector.

   What would strike a ghoul dumb

   Is the juice of a plum.

   Not a one can resist that nectar.
** Fake moon
Baby penguin, tubular

Angst teen penguin

1 king penguin in business suit with fake suitcase, maybe a rock

2 queen penguin
* Sweet
** Yum
Shallow callow marshmallow

Build a bridge of friendship from mashmallow

Deep chasm between us
** Yumm
In my weakness I am meat.

Not the cheapest, bad to eat.

My body fails. All I find

Are wet entrails 'round a mind.
* Train/star-related
** Going Home
   Riding home backwards,

   Guarding the front of the train.

   The Sun's in my eyes.
