* Spring 2022 Previews
** OP
Eyo,

New season, as our eyes notice buds on previously bare branches, so do our nostrils detect the scent of new anime. Switching tracks, this time I'm categorizing my anime thoughts by igneous rock textures.

** With a smooth, almost liquid appearance, glassy rocks have no distinctive crystallization and are easy for me to decide to watch.
*** Komi-san wa, Comyushou desu. 2nd Season
Not much to say, I liked the last season and still haven't read the manga, so I'll probably enjoy this season.

** With mineral grants large enough to be seen with the unaided eye, phaneritic rocks have some distinguishable merits even before they (are thrown in the) air.
*** Dance Dancce Danseur
I like the manga so I don't feel an obligation to watch this for the story. If it fails to improve on at least some aspect of the work, I'll drop it. If I'm not misremembering the pacing of the manga, the anime might have to move things around or cut portions to end at what I would consider a "satisfying" place in one season (but not sure it'll just be one yet). That could be a good thing or not, as portions of the manga drag. There are two chief animation directors, who each seem fine, which may or may not be a bad sign for the animation quality, not sure.

*** Ao Ashi
Ao Ashi is one of my favorite three recent soccer manga (along with Days and Be Blues), but I was somewhat surprised it was being animated at all, and by Production I.G. even more so. The character designs in the early parts of the manga can be both very loose (in the sense that they fluctuate between chapters) and angular. The show definitely standardized them in the trailers, which is totally understandable, but a tiny bit disappointing.

I'm in for the chance that there are some Haikyuu-esque animation sequences, which I think Ao Ashi lends itself to (since the manga at least makes use of the loose character designs to have some very expressive soccer and character moments).

The director (Akira Satou) hasn't helmed a show I recognize yet, but has been around for a while. Some of the key folks (the director, one of the character designers, director of photography) don't seem to have worked for a couple years, which I'm choosing to take as a sign that this show will have zero production issues.

*** Spy x Family
Yay, another good manga is being adapted (probably) well. The voice actors for Loid and Yor are "cool"-er than I had in my head, and Anya is more child-like (guess they decided that children should have children's voices, instead  of the higher-pitched aging comedian I'd imagined).

*** Summertime Render
The manga is on my list of series to get to, but the anime trailers look good, so guess I'll start with this.

The director (Watanabe Ayumu) has a fairly long track record (lots of Doraemon movies that I have no knowledge of), but specifically directed Kaijuu no Kodomo which was a very beautiful movie that was sea-themed. And the main background artist (Kusanagi) worked on nice stuff like Kakushigoto, Ride Your Wave, and Super Cub (which had really nice backgrounds).

** With conspicuous phenocrysts in a fine-grained groundmass, porphyritic rocks are not as phanerish as phaneritic rocks, but they might have a cute crystal or two.
*** Paripi Koumei
There's very little animation in some of the promos, but the character animation shown is consistent and it looks like a fun enough premise that the animation doesn't matter much. Not sure if this will be as silly as Zombieland Saga, but could still be good. Looks like it's the director's (Honma Osamu) first full series after working on a bunch of stuff I'm not familiar with as an episode director and producer (so not coming from an animation background, which probably matters less for a comedy series). Oddly, the same art director (Higashi Junichi) as Cowboy Bebop. except it's not that strange because he's done a bunch of bad-to-good things apart from that.

*** Aharen-san wa Hakarenai
Looks like pure fluff. So very well might watch it. Plus, one of the directors (Makino Tomoe) directed Kotarou Lives Alone. I don't expect the same level of bitter-bitter-sweet as Kotarou, but just the sweet would be enough to watch.

*** Kawaii dake ja Nai Shikimori-san
I also like this manga, but don't feel a strong compulsion to watch this show (with it's anime-ification of the character designs serving as one turn off).

*** ONIPAN!
Not sure what this is about (except for onis and underwear), but it's short so I'll try it.

** With different compositions that are indistinguishable from each other by the unaided eye, aphanitic rocks are for plebs.
*** Love All Play
After watching Ryman's Club this winter, Love All Play looks likely to also fail to animate badminton well. But without the more unique premise of adults doing sports, I have no interest in this.

The director (Takeuchi Hiroshi) has worked on a mix of great stuff (Mob Psycho 100 II, Cowboy Bebop) and meh stuff, but mostly as an animator/storyboarder. The two series they've directed fall squarely into the meh category for me. Also a bit odd that three people are credited for the script (I like work that all of them have done) along with an original creator. Not sure if that is unusual, but can't remember seeing another series like that recently.

*** Gunjou no Fanfare
The only way I would watch this horse boy anime is if it had a stinging critique of class structure (or turned into an isekai where the boys had to chariot race for their lives). So, let's watch the trailer... Hm, "If something's bothering you, want me to make you feel better?" "They say you have to become one with your horse!" "Is this the price I paid for quitting being an idol?" The newest horse idol show isn't what I'm looking for. Plus, the horse animation looks silly.

*** Tomodachi Game and Deaimon
Rather read the manga if anything.

** ED
Oye,

Eric
** Follow-up
*** Re: Aharen-san
No way this is loli-bait. I'll have you know that the main girl only gets in between the main guy's legs once in the first episode!

*** Re: "Eye asses"
I found this hard to imagine, but I'll keep trying. Is the pupil the asshole, because of the illusion of depth? Or is the optic nerve coming out of the ass? Or is the eye socket itself the ass and the eye is the "butt" plug?

*** Re: Leading me wrong before
I can't remember you leading me wrong before. And you know the old saying, "You can lead a horse to water, but you can't make them watch shows they don't want to." By which I mean I take responsibility for choosing to consume my fair share of watered-down anime.
