* Winter 2022 Previews
** OP
Owdy,

In keeping with last season's easy to understand analogy to theme park height restrictions, this time I am sorting my anime thoughts according to the next most logical schema. Oreo flavors.

** The bright, refreshing Oreo Golden Sandwich Cookies, Lemon Flavored Creme.
The hope of the lemon and the sheen of the gold come together to make my mouth water (the perfect level of moisture for anime consumption). The only drawback is the lack of chocolate:
*** Sabikui Bisco
I'm psyched for the shonen anime about rust.

The scriptwriter (Murai Sadayuki) has worked a lot of projects I like (Satoshi Kon films like Perfect Blue and Millenium Actress, and shows like Kino no Tabi) as well as adapting series I like but have not watched (the anime Blame!, Sidonia no Kishi and Natsume Yuujinchou), so I'm curious to see how it turns out.

*** Akebi-chan no Sailor-fuku
There was a lot of neat character animation in the first promo, so I'm definitely checking this out. I've read the first couple chapters of the manga, and it seems like a sweeter slice-of-life (but with a bunch of ecchi shots of high school girls which I did not catch in the promos. It's somewhat hard for me to imagine that an anime would be less ecchi than its source material).

The art directors worked on Horimiya (which had a similar, dramatically sunlit vibe). And I'm curious to see what the character designer/animation director (Kouno Megumi) will do, having worked on some fun projects as a character designer (FGO: Absolute Demonic Front) and more as an animator (Shigatsu wa Kimi no Uso, Spacy Dandy, Kill la Kill, ...).

*** Sono Bisque Doll wa Koi wo Suru
Another sweet, ecchi adaptation. And if the animation quality drops I'll drop it, 'cause to me the direction and character designs were unappealing (compared to the manga) during portions of the promos.

The director (Shinohara Keisuke) is a bit of a mystery to me. They've worked on some stuff I really liked (Devilman: Crybaby, Wonder Egg Priority, Flip Flappers) but the only thing they've fully directed and I've watched was Black Fox (which admittedly had fun animation, but ultimately wasn't entertaining).

*** Tokyo 24-ku
The third CloverWorks anime on my list. At this point, I'm hoping that one gets delayed a la Wonder Egg Priority, rather than having the quality drop for one or more of these. (Note: After writing this, it seems like this might be the odd one out of the bunch). The first promo makes this seem like a Minority Report update (with the police force in this world trying to preempt crime).

This will probably mean more to you, but the director (Tsuda Naokatsu) was part of the directorial group in JoJo parts 1, 3-5. I'm more intrigued by the script writer (Shimokura Vio) having worked on Puella Magi Madoka Magica and Steins;Gate and character designer (Takahiro Kishida) having done visually similar stuff for Haikyuu!, Durarara!!, and Baccano!).

** These cookies hide their light under a bushel. White Fudge Covered Oreo Sandwich Cookies, Holiday Edition:
*** Koroshi Ai
The promotional videos look like a mix between a generic setup (amnesia and a lost family) and an interesting love story/mystery. I'm going to check this out in part because it seems like a shoujo/josei action story and I'm curious to see what that looks like.

Most of the staff seem closely tied to projects by this studio (Platinum Vision), whose work I've not watched so I'm worried that the animation quality will be erratic.

*** Eien no 831
This is just a single episode thing, but its directed and written by the director/writer of Higashi no Eden (along with other stuff that seems good but I've not watched).

*** Ryman's Club
A sports show about adults seems neat, and the animation in the promo looked solid. I'd be surprised if the animation quality didn't drop at some point, so having characters working through more adult problems could be a fun diversion. The promo only highlighted a traumatic experience with a former teammate and meeting an enthusiastic new teammate, which both seem generic as it gets, but hopefully that's just the setup.

Plus, the character designer (Yasuda Suzuhito) is behind the designs for Durarara!! and the art director (Kai Masatoshi) has done some interesting urban designs before (Ao no Exorcist and Subete ga F ni Naru).

** The classics. Oreo Caramel Flavored Creme Chocolate Sandwich Cookies:
*** Kimetsu no Yaiba: Yuukaku hen
Yay! More splish splash, swoosh slice action.

*** Genjitsu Shugi Yuusha no Oukoku Saikenki Part 2
Looking forward to the shift towards foreign policy (slash expanding Souma's pool of love interests still further).

*** Ousama Ranking
Yay! More Whish whoosh, smash smoosh action.

*** Vanitas no Carte 2nd Cour
Yay! More sip sop, suck sick action (in Paris).

** Why do these exist? Oreo Chocolate Sandwich Cookies, Birthday Cake Flavored Creme.
How would one's birthday be improved by the addition of these cookies? I only hope that someone has constructed an edible birthday robot and used these to cover its light sensors:
*** Tensai Ouji no Akaji Kokka Saisei Jutsu
I get the feeling that watching this would be a lose-lose scenario for me. If it's better thean Genjitsu Shugi than I'll feel silly watching that. If it's worse, I'll be watching a bad show. I get that the main character is supposed to be "lazy" in this one, so maybe the shows will be sufficiently different. But I'll wait on this to see if folks like it.

*** Kaijin Kaihatsu-bu no Kuroitsu-san
The setup (scientists in an evil organization) sounds funny, but the promo made it seem like more of a slapstick, ecchi show than I'd like. Add in that the director (Saitou Hisashi) and credit for series composition (Takayama Katsuhiko) have worked on a real mixed bag of shows, and I'll sit this one out.

*** Baraou no Souretsu
I'm tempted to watch this if only because I'm doubtful that the manga will every get translated. But the promo seems so gropey and melodramatic that I can't buy into it.

*** Tribe Nine
If I'm going to consume anything by the Danganronpa writer, I have the feeling I should complete the games first (or at least watch Akudama Drive).

** ED
Ow-bye,

Eric
