* Summer 2022 Previews
** OP
Howdy,

I like saying "howdy", so how'd you like a cow-poke themed anime preview? What? It's the rootin' tootin'-est thing you've ever laid eye upon? Shucks.

** Frank Boardman "Pistol Pete" Eaton
This guy lived to be almost 100, so that's a good enough reason for me to use him as an analogy for shows that I'm still watching from last season.
*** Summertime Render
Bloop, bloop, I am watching this.

*** Ao Ashi
Bleep, blorp, I am watching this.

*** Onipan
Blop, blap, I will probably catch up on this cause it's fine.

** William Frederick "Buffalo Bill" Cody
I recognize this guy's name. These are the shows that make me think, "I recognize this guy's name."
*** Overlord IV
My favorite story about the politics of a corporation trying to consolidate its position. I guess this season introduces some competitors?

*** Danmachi IV
I'm not super  excited to watch another season of this, but feel an obligation to keep going. As long as there are a couple exciting moments I'll feel justified in sticking with this.

*** MADE IN ABYSS
The market of values is fun, but I might have to reread the manga to remember stuff.

** Charlie Siringo
Apparently this guy became a Pinkerton, but was sympathetic to some union workers and may have prevented a few lynchings. These are shows that make me think, "Hey, this show may suck or it may be sympathetic to union workers."
*** Isekai Ojisan
Hmm, I'll watch this, but am not sure what to expect. The animation in the promo was alright, although the line quality was funky enough that I'm not sure if it's an indicator of an ambitious team or they just spent their budget on a filter and are going to cut corners somewhere else. I think the director (Shigeki Kawai) has done a bunch of action work in the past, but this doesn't look like an action-heavy show. And I'm not sure how ecchi this is going to be, cause the manga cover looks like it could go either way and the studio previously did Ganbare Douki-chan, which has, ahem, caught my eye on r/manga, but I don't know if the anime was any good.

*** Lycoris Recoil
The promo video didn't catch me, but I like the promo image and the description. Who doesn't want to see a silly cafe show?

I like the character designer (Imigi Muru)'s manga, but don't know the scriptwriter (Asaura)'s work other than some peripheral knowledge that Ben-To seems shlocky.

Note: I've watched the first episode since writing the above comments, and decided that this could be more than a silly cafe show, but could also be super shlocky.

*** Bucchigire!
Criminals with magic swords fighting in the dark with funky compositing, sounds neat. There's one shot towards the end of the second promo video where the camera is dynamic, but I'm not convinced it'll be an animation marvel. Just making me care about most of the eight main characters would be enough. I guess Geno Studio did Golden Kamuy which I didn't watch, so I don't know if they'll pull off these very 2000s anime designs.

*** Warau Arsnotoria Sun--!
I'm gonna watch this, even if it looks like a self-serious Little Witch Academia. The director (Naoyuki Tatsuwa) is a former SHAFT-y, and there were some visually impressive moments in the teaser (like the very first shot which does a weird zoom-out/pan-down combined with going into a fish-eye view).

*** Yurei Deco
Wooo! I don't know if this will actually be good, in the sense that it looks like a childrens' show. But the description sounds like it could be setting up a mystery.

Note: I've since watched the first episode and it's a whimsically portrayed dystopia (reminiscent of Yuasa's Kaiba) but with very contemporary elements. I'll like it more if this has some interesting mystery or asks unexpected questions about society, but it's also a fun world to watch the characters move about in.

*** KJ File
I know nothing about this, but the director (Funada Akira) produced something called Business Fish, which I've not watched but has convinced me this will be amazing.

Post-watching the first episode (and only translated episode I could find) of Business Fish: I like Business Fish, but would also not be surprised if the minds behind Business Fish created a non-Business Fish show that I didn't like as much as Business Fish. Buiiiisinessssss Fiiiiiish. That's a fish, that does business.

** Theodore Roosevelt
Is this guy best described as a cowboy? Probably not, but Wikipedia decided to put him on a list of cowfolks, and who am I to squabble with strangers on the internet? These are the shows that make me think, "Is this best done as an anime?"
*** Yofukashi no Uta
I like how colorful the promo is, but not sure if that's enough for me to watch this. I like the manga well enough though.

*** Hoshi no Samidare
If this isn't good, I'm going to be so sad.

*** RWBY: Hyosetsu Teikoku
All I really know about RWBY is that one of my favorite mangaka (Miwa Shirow) took a hiatus from Dogs: Bullets and Carnage to presumably (or maybe just coincidentally) work on the RWBY manga. And never went back to Dogs. Boo. I don't love the look of the CG.

*** Kuro no Shoukanshi
Why does the main character have a knife behind his ear?

** ED
Tata,
Eric

