* Winter 2021 Reviews
** OP
Howdy,

Now that the last episode of the stuff I cared about has aired (or been significantly postponed), here's my review/commentary dump. I figure we watched a bunch of the same stuff, but I'll try to warn you if I might spoil something and I'll write it in white text (guess you should just preemptively delete this if you don't use a white background for your email reader).

** Wonder Egg Priority
This by far exceeded my expectations going into the season, and I love so much of what it did. (In case you've not read the blog posts about flower language in the show, I recommend them.) I enjoyed the animation and direction throughout, as with most anime production almost every episode had a different episode director under the series director and their different motifs or points of emphasis were really fun. The monsters were ridiculously grotesque and their battles were cathartic and gripping.

Leaving aside the wait for the final episode on the basis of completeness, I take issue with the ... I was going to write about how I don't think the scientists' backstory is really necessary to the story. But, I enjoyed their story on its own merits and, upon reflection, the idea that these two (differently) demented scientists (and our broader society) are trying to use teenage girls to conquer death is fine.

(12 out of 13 episodes)

** Jujutsu Kaisen
Everything I want from a shounen manga adaptation! (Ignoring the Mob Psycho-type visual reinventions.) It had impact frames! It had rockin' music! It had running and fighting on rooftops! It had impact frames! It had comedy that wasn't usually funny but provided some relief from the action.

(9 out of 10 fingers)

** Re:Zero
I found the previous cour of Re:Zero really underwhelming. The strengths of the previous seasons - shock value with the action and plot developments, really careful direction to make up for limited animation, good character animation - all went in and out (obligatory, "for me"). But, this season really pulled me back in. I wouldn't say it had the consistent visual polish of season 1, but it was at least interesting and at times beautiful. Whereas the shock I felt during and after season 1 came from grisly battles, this season I was more overwhelmed by the lore. Apart from rounding out a lot of characters and providing motivation for why I should care about these nerds, this led to some moments of catharsis that I hadn't got in earlier seasons. This season, Subaru's early interactions with Emilia weren't my favorite at the time (I figure you've seen this, but I won't give the exact quote from my notes, just in case) (yes, I take notes on anime), but in the context of Emilia's persistent self-doubt/-hatred I valued it more.

I can't write about this season without mentioning the eyes. THe eYEs! I don't have (a) good enough memory to remember if they were such a big thing in the previous seasons, (b) enough motivation to rewatch it or read the source material to find out if this is really a new motif or something they've been building on. In case you've not watched *SPOILER WARNING*:

In the confession scene, they started off quite heavy-handed. Emilia's reflection was almost always in Subaru's eyes whenever he was shout-talking to her, and Emilia's eyes stayed dull or the camera just stuck to her lower face. Until, Subaru finally was reflected in her eyes towards the end. Then, in episode 7, they leaned hard into the "camera sticking to the lower face"-thing, especially with Echidna. At the end of the episode, when the scenes of Subaru, Roswaal and Emilia showed a lot of eye, it struck me as particularly effective. Finally, they did a similar "dull eyes or lower face only until she has his reflection in her eyes"-thing between Beatrice and Subaru, plus the added physical element of Beatrice pushing Subaru away with her eyes covered by shadow. They definitely have done the "camera to the lower face"-thing before, but I figured that was down to not wanting to animate an entire face. And the reflections have been used in plenty of other anime, but usually at *the* climax of the narrative as opposed to a series of sub-climaxes. It worked for me this season, but if this becomes a bigger trend, then I might get sick of it.

(1 out of 2 oni)

** Mushoku Tensei
In my prospective look at Winter 2021, I wrote something like "I'm wary about this because it is being handled by a new studio". I was totally wrong to be worried (and it turned that it's not really a "new" studio, just a dedicated team) and this had some great animation and world-building. I only dipped into the reddit discourse occasionally, but there were some fun threads about how much attention the show paid to the finer details of living in a medieval-like world, so it was fun to feel like I could immerse myself in even the minutia of the show and find that thought had gone into all the choices.

Rudy sucks. As far as I understand, this is down to the source material, but I don't see a plot-related reason that he has to molest women. Is it in order for the audience to understand that he is socially uncomfortable? He's a NEET from another world, we can assume he's awkward. Is the author saying that all otaku are waiting for the opportunity to steal girls' underwear? Are they making fun of this idea, playing it up for irony? Is this related to the trauma from his past? The most justifiable example of verging-on-creepy-behavior was the exchange with Sylphy; I wanted to cover my eyes, but it felt like it served some narrative purpose. Heck, maybe it would even fuel some character growth? I'm still waiting for that.

Honestly, it bugs me because it's one of the few things I dislike about an otherwise fun show.

(4 out of 5 Greyrats)

** Horimiya
Going in, this was going to be my fourth retreading of the Horimiya relationship and I was hesitant that another take could have anything new to say. By the end of the season that feeling has come back, but I really liked the easy atmosphere of the early episodes. Because the anime adapted "critical" moments from the manga, it really leaned into the Miyamura perspective over Hori's. Now that I think back, the manga probably does that as well, but it just stood out a bit more here.

(Short-haired Miyamura out of long-haired Miyamura)

** Tenchi Souzou Design-bu
My only note on this was: "fun". Playing the game of "can I guess which animal they're talking about" was always enjoyable. While I don't think it was hilarious, there were funny moments and ideas that I laughed about internally.

(2 horses up)

** Log Horizon
As with previous Log Horizon seasons, I find myself slightly confused at what exactly was the magnificent strategy Shiro pulled off (voter registration?). On the flip side, I enjoy the "Aw, they grow up so fast" antics of the young'uns more than I expect.

(Lv 65 out of "whatever the max level is")

** Osomatsu-san
Last cour, they introduced a couple of robots who were just a manzai act with two tsukkomi and I didn't find them funny. This cour, the robots played a smaller role (still too prominent for me) and I got more of the silly skits I wanted. It still wasn't enough to leave me wanting more Osomatsu-san, so I would probably sit out a hypothetical fourth season.

(Triplets out of sextuplets)

** Jaku-chara Tomozaki-kun
The Smash Bros anime! Based on the synopsis and trailers, I was hoping for something along the lines of OreGairu (which I've liked for stretches). The setups were comparable, an observant loner kid becomes involved with the popular kids and their relationships. At times, Jakuchara was silly (passionate speeches about Smash Bros is inherently ridiculous) or thoughtful ("You can't say life is a 'bad game' without trying to play" isn't profound, but I appreciate the effort). But I am coming away having watched a season of dialogue that was cliched right up to the point of parody, girls groping each other, and high stakes banter. A pitch-perfect OreGairu successor!

I thought of a few alternative pitches for the show:

- Experience the slow realization that the most popular girl in school is a sociopath.

- Watch how close we can get to saying "romance is fake" and "dating is a contest to nab the hottest girl you can" without coming right out with it.

- How many times can we pan over a girl's body without creeping you out? Oh, what if we do it ... slooowly.

(Four out of six Marths)

** Urasekai Picnic
After the first episode, I was kind of into the idea of an episodic suspense/horror show. Maybe it would even develop on a neat premise (beings visited Earth and left behind artifacts that we don't understand). I dropped this after the seventh episode, so I can't say with certainty that they failed at this. But, I can say "they failed at this" during the episodes I watched. The animation wasn't horrible but was never appealing. If it was supposed to be episodic, then there was neither a complete wrap-up to any of the separate storylines nor a compelling thread to the season. If it was building to a mystery, I didn't catch enough hints of that. I liked the idea that the characters have different reasons for exploring the Otherside and were building a relationship over time, but not enough to keep watching.

(A sigh out of a scream)

** ED

That's it.

Dunko,

Eric

** PS
*** Toutotsu ni Egypt Shin
The premise was fun for a few episodes, but I'm glad that this only had 10 episodes.

(7 out of 13 Egyptian Gods)

*** Shirobako Movie
Not sure if you watched the series, but this hit a lot of the same self-aware silliness that made the series fun. Some of the pseudo-cameos from anime industry people didn't sit well this time. Maruyama Masao (co-founder of Madhouse and founder of MAPPA) being forced to resign and start a curry shop. Ouch.

(2 out of 3 Aerial Girls Squads)
