* Chains
** Letter
*** Aliens
Aliens spend decades sowing great terror.
*** Few
Few women need dingus spouses
*** Today
Today you understand dreams.
** Syllable
*** Time
Time mice cite time mites.
* Long
** Unruly, A-Z
   All alphabets allow amusement.

   But becoming bored bites.

   Consider consuming comforting creations.

   Dandelions, daffodils, dingoes, doggies.

   Every entertainment entails effort.

   Frequently, fear freezes feet.

   Graciously grief grants growth.

   Hope, however, houses horror.

   Insistently incapable instances interfere,

   Jovially joining joyless journeys.

   Kindness kills kids’ kisses.

   Lovingly lowering local lonesomeness.

   Mechanisms melt mental measures,

   Nonsense nobody notices normally.

   Opinionated operations openly opine,

   Practically preaching precious practices.

   Quitting quells questions. Quiet.

   Runts rule rusty ruins.

   Spittle speckles spotted, spiraling 

   Towers. Tolerance to toxicity 

   Unavoidable. Unless unfortunates unveil

   Venerable Venn-shaped venom vents.

   Without wind, will withdraws,

   Xenophobic. Xenial Xeresian xenolith

   Yoo-hoos your youth. Yoinking

   Zealous zebras and zeppelins. Zeugma.
** Carrot cartons
Carrot cartons carry carrion carefully,

'cause careless carting can cause camel catastrophes.

Clasping, clenching clippers closely. Clue.

Crabs creep. Crippled crocodiles crunch! Cry.

Flags flew flickering, floating, fluttering, flying.

Fleeing fleas flew to flexible fleurs.

Frame freeze - frictionless frozen fruits frying.

Fresh from France, Frankie's frumpy fruits frustrate

Grandfatherly gremlin grifters growl gruffly.

Long-lost lovers lose loyalty.

Monkeys moan morosely, moreover, most moan more on Monday.

Track trainers trade tragedies, traveling by train.

"Trading Treats tricks trolls truly try."

While whiffing, white whiskers whisper, "Which?"
* Short
** Perfume
Perfumery performances,

Frantically framing fragrances.

A romantic aroma arose.
