* Long
** Unruly
   All alphabets allow amusement.

   But becoming bored bites.

   Consider consuming comforting creations.

   Dandelions, daffodils, dingoes, doggies.

   Every entertainment entails effort.

   Frequently, fear freezes feet.

   Graciously grief grants growth.

   Hope, however, houses horror.

   Insistently incapable instances interfere,

   Jovially joining joyless journeys.

   Kindness kills kids’ kisses.

   Lovingly lowering local lonesomeness.

   Mechanisms melt mental measures,

   Nonsense nobody notices normally.

   Opinionated operations openly opine,

   Practically preaching precious practices.

   Quitting quells questions. Quiet.

   Runts rule rusty ruins.

   Spittle speckles spotted, spiraling 

   Towers. Tolerance to toxicity 

   Unavoidable. Unless unfortunates unveil

   Venerable Venn-shaped venom vents.

   Without wind, will withdraws,

   Xenophobic. Xenial Xeresian xenolith

   Yoo-hoos your youth. Yoinking

   Zealous zebras and zeppelins. Zeugma.
