* Summer 2022 Reviews
** OP
Howdy,

Why did the me from several months ago spend time looking up cowboys? Not sure. Um, here are my reviews for the summer season.

** Frank Boardman "Pistol Pete" Eaton
*** Summertime Render
Just have to get a couple things out of the way up top. First, I'd already read the manga by the time I watched most of these episodes (started them both at around the same time but read through the manga first and then caught up with the anime as it finished airing). As a result, most of my review will focus on the anime-specific parts of the series. Second, when I mentioned that I was doing a little scavenger hunt watching this, you'd suggested that I was keeping an eye out for which characters were shadows. That was a good guess, but not quite. While watching the first episode, I thought there were a lot of visual motifs with light and camera effects, so I was collecting examples of that. It was fun to speculate about what would last through the series as opposed to just being the quirk of a particular episode's director. And there was one thing I only noticed well into the series and then ended up thoroughly confused with by the end. These are all fairly disconnected, so I'll just list them out: (just to be clear, all these links have spoiler material in them)

 - Reflections: For a show that deals with impersonation, this felt like a fairly route one visual metaphor. But despite being introduced in the very [[https://imgur.com/a/0YUXZML][first episode]], it didn't reoccur as often as I'd [[https://imgur.com/a/z6oOj6R][hoped]].

 - Shadows: "This is a show about evil shadows, of course they have shadows in it." Yeah, I agree but I'm referring to [[https://imgur.com/a/owbEOi5][storytelling shadows]].

 - Bokeh: Did you know that bokeh came from the Japanese "boke" meaning haze or blur? Me neither. Don't think that etymology matters, but the show sure used a [[https://imgur.com/a/7bpQ5Ag][lot of it]].

 - Eye reflections: This is the one I didn't cotton onto for a while, and when I did it was more for the intensity it had in that particular [[https://imgur.com/a/Pf2HSuv][instance]]. But then I started to form this theory that the two dominant eye reflection types in the show: (1) big circle at the top with little ovals towards the middle and (2) just two little ovals towards the middle, might have some meaning. Maybe the good guys have type 1 and the baddies have type 2 (and Shinpei having both in episode five was due to him having Haine's evil eye?). By the end of the series I don't think I can stand by that hypothesis, but it was fun to [[https://imgur.com/a/a1MYjZa][look out for]].

 - Blur: There were a lot of instances of characters being stricken by some information and getting a close-up of their reaction where the camera wiggles around and [[https://imgur.com/a/5bhmTlc][blurs]] in and out. There were so many examples of this in the last few episodes that I just gave up screenshotting them.

 - Miscellany: These either appeared too [[https://imgur.com/a/ayvaXhQ][infrequently/inconsequentially]] (as far as I could tell) or appeared in a single episode and therefore felt more like that episode director's personal [[https://imgur.com/a/INyJuOy][quirks]] than a series-wide choice.

8/10 Best explanation for why one of the characters is wearing a bathing suit throughout the series for Ushio's "I can fight in it"

*** Ao Ashi
I definitely enjoyed this adaptation, but that's more due to: (a) my liking the source material and (b) occasional bright spots of animation or emotional climax. That is to say, there were big chunks of this show that were not fun. But that is only relative to other anime that I would normally choose to sit through 24 episodes of. In comparison to other sports anime, or to other soccer anime specifically, this was good.

There were a couple of fun animation thing-ama-jigs that I watched for. The use of rotoscoping, which I think first appeared in episode two with a scene of Ashito turning, was sort of sprinkled through the first cour. And it featured quite heavily in the second cour's opening, but not so much in the actual episodes. In return, the animation quality during the second cour took a step up (in general, cause there were also plenty of extended still shots and cop outs). It felt like there were a few animator favorite characters - Togashi, Yoshitsune and Kaneda - who got a disproportionately high level of movement quality. Maybe someone at Production I.G. just loves the lanky bigboys?

7/10 Most Physics-Defying Animation for the CG soccer ball that never changed size as it moved towards the camera

*** Onipan
Since you seemed surprised that I was actually watching this, I have resolved myself to wholeheartedly defend this show. It's a show about young people, sorry, oni (onii? onieces? onipodes?) trying to change the Japanese peoples' perception of oni. They demonstrate remarkable ingenuity, bravery, and pure-heartedness to overcome every obstacle in their way to make Japan a more openminded place.

Is what I would say if this was a kids show. Which I guess it is, but a Japanese kids show from Wit Studio who seem to have allowed the production to have all the hallmarks of a children's show (long...pauses...in...the...dialogues, bright colors, bite-sized episodic plots) but with some treats thrown in for a dweeb like me.

That's not to say this is a great show, or even particularly good. It just had enough morsels of interest spread throughout to keep me watching. The comedic animation could be quite good, with fun [[https://imgur.com/a/jRpF203][smears]] and reaction [[https://imgur.com/a/NXjcIdT][shots]]. Most episodes that weren't contributing towards the series plot took the form of a parody, from battle towers, to [[https://imgur.com/a/FmEnIuv][Yu-Gi-Oh]], to [[https://imgur.com/a/rk0hfvS][idols]], to [[https://imgur.com/a/QRzw0vv][youtubers]]. And the sense of humor, while usually not my thing, could be amusingly [[https://imgur.com/a/I7LjPqS][self-aware]], [[https://imgur.com/a/bUGsvLg][dark]], or over the top.

6/10 Most surprisingly well-animated fight scene for episode 7's [[https://imgur.com/a/0f4Y4iK][sea battle]]

** William Frederick "Buffalo Bill" Cody
*** Overlord IV
There was politics in this season. And there were fights, I guess. Oh, and there were a bunch of countries. What, that's not just another way to say "politics", it's ... geography or something.

I can't get over that Ains kept going on about how he wants friends or to nurture independence among the Nazarickians, but he can't admit to any shortcomings. Sure, it's comedy at first, but if I'm expected to seriously buy that Ains is lonely or fatherly, I can't also laugh at his glowy, green straight man act.

And I thought the politics were just an extension of that same dichotomy and the fights were kinda ketch' (weak sauce).

4/10 Best dwarf for the dwarf who was willing to straight-up "British Empire" the artifacts of his own peoples' cultural heritage

*** Danmachi IV
I can't get over that this eleven-episode season ended on a cliff-hanger when it felt like there were at least three episodes of unadulterated fluff. At some point in the season, I thought there could be a well-conceived arc to the episodes. We get to see the gang get back together ("Oh, it's wingman." "Oh, it's wingwoman." "Oh, it's 'girl who likes Bell'."), then they get into a sticky situation where the group's reliance on Bell is exposed, but there's a little character development, and finally they get into an even stickier situation but this time the group grows and is able to pull them through it. Welp, maybe next season will be fun.

5/10 Best supporting actress for Aisha's boob cloth (everyone applauds because it should have won a couple seasons ago, but was overshadowed by Hestia's ribbon)

*** MADE IN ABYSS
I was in a state of constant, minor confusion by the different characters' motivations in the city and still don't really understand why Wazukyan and Belaf made a bunch of decisions. But I was still grossed out, sad, and hyped up at the appropriate moments. There were lots of vagina monsters, sorry, hollows. And the climactic battles were exciting. I'd only recently watched the third movie, and the action animation in this series didn't live up to that standard, but it feels unfair to compare a television series and a movie.

8/10 Best fuzzy pink penis character for Maaa

** Charlie Siringo
*** Isekai Ojisan
Well, better luck next season.

*** Lycoris Recoil
Lycoris Recoil isn't really for me, but it was a fun watch. The action scenes were exciting and the relationship between Takina and Chisato was a neat driving force through the season. After establishing their opposing viewpoints on the Lycoris, killing, and underwear, we got to see them grow closer. I would say in a lot of little ways, that closeness was due to Takina changing - not immediately killing everyone, being willing to sacrifice her standing with the Lycoris, taking an interest in the cafe (in ascending order of importance, of course). Not until the very end would I really say Chisato changed, and even that's not really a character change, she was just (spoiler) forced to keep living by Mika and Takina. But whatever, Majima was a more interesting villain than I expected, just as a consequence of questioning the conceit of the show "teenage girls protect Japan by shooting guns".

7/10 Best speculative architecture for the semi-destroyed building that Japan inexplicably decided to preserve as a monument to terrorism? Or as a monument to Chisato saving people? But no, she's a secret, right?

*** Bucchigire!
I dropped this after 10 episodes. It was the last show I was waiting on watching before sending my reviews and I suddenly realized while out on a walk and contemplating anime, "Hey, watch where you're going! Jesus Christ!" And as I crushed that ant below my shoe, the fragility of life and also how much more entertaining non-Bucchigire! shows can be struck me.

In terms of actual critique, the texture that they placed over everything sometimes added to the vibe of the show, but often (especially when placed over a darker scene) looked messy and felt like a ripoff of Odd Taxi's textured look.

Uh, for a show with color-coordinated characters, it was a bit of a weird throwback that the two most prominent (not very prominent) female characters (the girl in the Shinsengumi and the sister of that sheriff from a single episode) were both pink.

*** Warau Arsnotoria Sun--!
This is one of the finest mystery shows of the last decade. In that it is apparently based off of a game, but I never had any idea what kind of game that could be. There are girls, so is it a dating sim? I guess there's "fighting" in the OP and a couple episodes, so it could be some sort of action game? There's music, so it could be a rhythm game. Every episode aludes to some malicious group of "knights" that could storm the school, so maybe tower defense? I still refuse to find out what this game is, because the anime sucked.

I sat through 12 episodes of two characters drinking tea (there are five main characters, but I think of them as only having enough depth for two characters in any self-respecting series), and maddening allusions to some broader story that I never got! I wanted to write that this is the ultimate edging anime, but that is too generous to the term. This is like eternally being an awkward middle schooler who tries to walk past people as they sneeze to get sexual gratification.

Where plot is [[https://imgur.com/a/9sCS237][concerned]]. There is a succession of minor [[https://imgur.com/a/im9exSC][conflicts]] but nothing consequential enough to really matter in subsequent [[https://imgur.com/a/BWlxNxB][episodes]]. What bugs me most is that there are weird moments that slightly raised my expectations over the course of the series. Apart from the obvious "big bad" that was setup throughout, there was a threat to the safety of the girls' school introduced in the first couple episodes that was completely ignored in the remainder, they left the school in one episode and alerted the "big bad" but then *bloop-blap* nothing resulted. Heck, one girl often doesn't "have enough mana for biscuits" and at the end she "has just enough mana". That's probably the only satisfying character arc in the show, and I don't even understand what "mana" is in this world, 'cause it sure as heck isn't being used for exciting magic junk!

Regarding aesthetics, the character designs were obviously too complex for the animators, who are forced to rely on a whole lot of cuts with only a couple frames of movement or just lose any consistency in character models. The backgrounds can be nice, but the direction is very vanilla so this whole magical school campus they were establishing felt stale after a few episodes.

4/10 Cutest domestic servants for the fairies (library, kitchen and miscellaneous)

*** Yurei Deco
Finally, an anime PSA for kids about the dangers of misinformation and social media. My biggest gripe with the show is that I couldn't get over that comparison and it was hard to look for any deeper meanings (if they existed). But the narrative was well put together (a lot of episodic adventures that fleshed out the detective club members' backstories and fed into the larger mystery of Phantom Zero), the world was fun (a very bleak, utilitarian cityscape underneath kind of tacky glowing shapes), there were some excellent character designs (who doesn't love a business cat?), and moments of squishy, stretchy, shapey animation. Just not as much squishy, stretchy, shapey animation as I was hoping for. I also couldn't get out of my head that if this was a more Yuasa-ish production, the digital worlds would have been way more psychedelic and less like a Bauhaus-loving but window-fearing architect's renderings.

Still, there were good high points, like the digital world in the zoological episode and the search for a mystery ramen stand.

7/10 Best names that I should probably think about the intended meanings of, but just haven't for Tom Sawyer city, Mark Twain, ... Oh, "The Adventures of Huckleberry Finn" -> Hack-Berry-Finn, that's something  at least.

*** KJ File
As far as I can tell, none of this ever got subtitled.

** Theodore Roosevelt + Whatever I didn't write about before the season but ended up watching
*** Hoshi no Samidare
I dropped this after watching the fourth episode, where this little gem of a [[https://imgur.com/a/FKD5aIL][frame]] appeared.

This lowered my opinion of Mizukami Satoshi.

*** Musashino
I guess this is an advertisement for some locality in Japan. And they chose to promote their region in the form of a [[https://imgur.com/a/C0hb9Da][memeworthy]] anime? I wouldn't say this was good, but it was short.

5/10 Best sport for [[https://imgur.com/a/1kqtlGG][UWAAR]]

*** Fuuto Tantei
I gave this one episode but was not into it.

*** Cyberpunk Edgerunners
Wowwie Maui. Now this is how Warau Arsnotoria should have been adapted. I can just imagine those little girls absolutely high out of their minds on Earl Grey jamming scones down each others throats until they burst.

This is basically the peak of the CGDCT* trope. I will never play this game, but gosh darn did this anime make me aware that there is a game called Edgerunners 2069!

Now that I've gotten all that out of the way, time to get down to bras tax. I thought the show did a great job of fitting a satisfying story arc into ten action-packed episodes. I couldn't point out any extraneous scenes or characters and just about every character's decisions and reactions felt justified in the universe's logic**.

The action was pointy, stretchy, colorful, and violent. I enjoyed the few times they would repeat a passage of a battle from several angles. There are a couple choices/scenes that will stay with me for a while:

 - The really superb, Hellboy-esque (or Trigger-esque, but it feels like it's been a while since they've done this kind of dark stuff) shadows during some of the action scenes.

 - (Spoilers) In episode six, the motif of Maine hitting David: Maine's early "Get away from me! Stop bugging me!"-type pushing away, his later "Get a grip! You couldn't handle Tanaka and now we're in deep shit!", and his final sentimental "So long kid" in the psychosis desert. Also, really liked David's shock and grief in the car at the end of the episode, with strong shadows over him.

 - (Spoilers) The whole scene with Doc Ripper in episode eight, from his loopy wiggling fingers animation to his disappointment and sadness as he sits along in the dark apartment at the end.

One bothersome thought I had was that this felt, a little bit in the overall tone but particularly in the music choices, like it was trying to evoke Arcane ('cause Arcane had an Imagine Dragons song and a lot of the music in this series felt similar). Guess I would have preferred something more electronic or jazzy, but plop rock was a choice.

\* Cyberpunk Gangsters Destroying Corporate Toughs.

\** Spoiler: I don't understand if Kiwi turned on Lucy and the gang because she blamed them for Maine and Dorio's deaths or out of greed or something I missed. Her dialogue with Faraday made me think she didn't blame them, but she had such a flat inflection that it was hard to read into her motivations.

8/10 Best counterargument to my preference for shady anime aggregators instead of watching on (in this case) Netflix for the crappy subtitles I watched the first eight episodes with (This might be a 9/10 anime if I'd watched with good subs (Yes, I mean the sandwiches (Yes, I mean the "cruel" definition of "mean" (No, this time I mean the "meaning of" definition of "mean"))))

** ED
Sigh-onara,

Eric
